### ISSUE TITLE
Can't import it by using NgIdleKeepaliveModule.forRoot() 

### ISSUE THREAD

**Issue by saiskarur** [HackedByChinese/ng2-idle#116]
Hi All,

I am new to ionic3 and angular, i have try to implement keep alive (keepalive) option for my app. I have install everting as per the instruction given by readme. Can you any one assist me to get it out of this issue.

TypeError: __WEBPACK_IMPORTED_MODULE_4_rxjs_Observable__.Observable.fromEvent is not a function
    at http://localhost:8100/build/vendor.js:64489:138
    at Array.map (<anonymous>)
    at DocumentInterruptSource.EventTargetInterruptSource [as constructor] (http://localhost:8100/build/vendor.js:64489:44)
    at new DocumentInterruptSource (http://localhost:8100/build/vendor.js:79729:23)
    at createDefaultInterruptSources (http://localhost:8100/build/vendor.js:79695:13)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:79698:32)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:79462:72)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:88799:73)

Operating system : Mac
ionic : 3
* **Browser:** all
node --version : v10.6.0
"@angular/core": "5.2.11",
 "@angular/http": "5.2.11",
        "@ng-idle/core": "^2.0.0-beta.15",
        "@ng-idle/keepalive": "^2.0.0-beta.15",

**Comment by batianusrey** [comment]
Hi @saiskarur , did you find a way to solve your problem or found an alternative?
